-- 코드를 입력하세요


SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d')REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R USING(MEMBER_ID)
WHERE M.MEMBER_NAME IN(
(SELECT M.MEMBER_NAME FROM MEMBER_PROFILE M JOIN REST_REVIEW R USING(MEMBER_ID)
GROUP BY M.MEMBER_ID
HAVING COUNT(M.MEMBER_ID)=( 
SELECT COUNT(M.MEMBER_ID) C FROM MEMBER_PROFILE M JOIN REST_REVIEW R USING(MEMBER_ID)
GROUP BY M.MEMBER_ID
ORDER BY C DESC
LIMIT 1)))
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC
