SELECT MONTH(START_DATE)MONTH, CAR_ID, COUNT(CAR_ID)RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING COUNT(CAR_ID) >= 1 
ORDER BY MONTH ASC, CAR_ID DESC

# SELECT MONTH(START_DATE)MONTH, CAR_ID, COUNT(CAR_ID)RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE CAR_ID IN (
#     SELECT CAR_ID 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
#     WHERE START_DATE >= '2022-08-01'
#     GROUP BY CAR_ID
#     HAVING COUNT(CAR_ID) >= 5
# )
# GROUP BY CAR_ID, MONTH
# HAVING COUNT(CAR_ID) >= 1 
# ORDER BY MONTH ASC, CAR_ID DESC