# SELECT (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA E1 INNER JOIN ECOLI_DATA E2 ON E1.DIFFERENTIATION_DATE
#        = E2.DIFFERENTIATION_DATE) FROM ECOLI_DATA
#        GROUP BY DIFFERNTIATION_DATE

# SELECT * FROM ECOLI_DATE E INNER JOIN
# (SELECT DIFFERENTIATION_DATE, MAX(SIZE_OF_COLONY) MAX_SIZE FROM ECOLI_DATA GROUP BY DIFFERENTIATION_DATE) TEMP
# WHERE E.DIFFERENTIATION_DATE TEMP.DIFFERENTIATION_DATE;

SELECT YEAR(E.DIFFERENTIATION_DATE)YEAR, (TEMP.MAX_SIZE - E.SIZE_OF_COLONY)YEAR_DEV, E.ID 
FROM ECOLI_DATA E 
INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE)DIFFERENTIATION_DATE, MAX(SIZE_OF_COLONY) AS MAX_SIZE 
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) TEMP ON YEAR(E.DIFFERENTIATION_DATE) = TEMP.DIFFERENTIATION_DATE
ORDER BY YEAR(E.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC