-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE)YEAR,MONTH(O.SALES_DATE) MONTH,COUNT(DISTINCT U.USER_ID) PURCHASED_USERS, 

ROUND(COUNT(DISTINCT U.USER_ID) / 
     (SELECT COUNT(distinct U.USER_ID) 
      FROM USER_INFO U
      WHERE YEAR(JOINED) = 2021)
    , 1) AS PURCHASED_RATIO
FROM USER_INFO U INNER JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE YEAR(JOINED) = 2021
 # JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR ASC, MONTH ASC
GROUP BY 1,2
ORDER BY 1,2