-- 코드를 입력하세요

# SELECT FLAVOR FROM FIRST_HALF WHERE FLAVOR IN(

        (SELECT FLAVOR FROM
    (SELECT FLAVOR, SUM(F.TOTAL_ORDER)+SUM(J.TOTAL_ORDER)TOTAL_ORDER FROM FIRST_HALF F JOIN JULY J USING(FLAVOR)
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
    LIMIT 3)
    SUBQUERY) 
# )


